language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env:
        - COMPILER=g++-4.8
        - COMP=gcc

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - COMPILER=clang++-3.7
        - COMP=clang

    - os: osx
      compiler: gcc
      env:
        - COMPILER=g++-4.8
        - COMP=gcc

    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++ V='Apple LLVM 6.0' # Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
        - COMP=clang

branches:
  only:
   - master

before_script:
  - cd src

script:
  - make clean && make build ARCH=x86-64 && ./DON bench 2>&1 >/dev/null | grep 'Nodes searched' | tee bench1
  - make clean && make build ARCH=x86-32 && ./DON bench 2>&1 >/dev/null | grep 'Nodes searched' | tee bench2
  - echo "Checking for same bench numbers..."
  - diff bench1 bench2 > result
  - test ! -s result
