name: Report issue
description: Create a report to help us fix issues with the engine
body:
- type: textarea
  attributes:
    label: Describe the issue
    description: A clear and concise description of what you're experiencing.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Steps to reproduce the behavior.
      You can also use this section to paste the command line output.
    placeholder: |
      ```
      position startpos moves g2g4 e7e5 f2f3
      go mate 1
      info string Available Processors: 0-31
      info string Threads: 1
      info string NNUE evaluation using nn-5227780996d3.nnue (105MiB, (82672, 1024, 31, 32, 1))
      info string NNUE evaluation using nn-37f18f62d772.nnue (6MiB, (22528, 128, 15, 32, 1))
      info string Network replica 0: Shared memory.
      info depth 1 seldepth 3 multipv 1 score mate 1 time 1 nodes 31 nps 31000 tbhits 0 hashfull 0 pv d8h4
      bestmove d8h4 ponder (none)
      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Anything that will give us more context about the issue you are encountering.
      You can also use this section to propose ideas on how to solve the issue. 
  validations:
    required: false

- type: dropdown
  attributes:
    label: Operating system
    options:
      - All
      - Windows
      - Linux
      - macOS
      - Android
      - Other or N/A
  validations:
    required: true

- type: input
  attributes:
    label: DON version
    description: |
      This can be found by running the engine.
      You can also use the commit ID.
    placeholder: DON
  validations:
    required: true
