name: Build WASM

on:
  workflow_call:

jobs:
  BuildWasm:
    name: WASM (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         include:
            - { name: "WASM32",              arch: "wasm32" }
            - { name: "WASM32 Relaxed SIMD", arch: "wasm32-relaxed-simd" }

    defaults:
      run:
        working-directory: src
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install and activate latest Emscripten SDK
        working-directory: .
        run: |
          git clone --depth 1 https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Download the used network from the fishtest framework
        run: make net

      - name: Build '${{ matrix.name }}' with Emscripten
        run: |
          source "$GITHUB_WORKSPACE/emsdk/emsdk_env.sh"
          em++ --version
          net=$(grep -oE 'nn-[0-9a-f]+\.nnue' "evaluate.h" | head -1)
          test -n "$net"
          make clean
          COMPCXX=em++ make -j build ARCH="${{ matrix.arch }}" EXTRA_LDFLAGS="--preload-file \"$net\""

      - name: Extract the bench number from the commit history
        run: |
          benchref=""
          for hash in $(git rev-list -100 HEAD); do
            benchref=$(git show -s "$hash" |
              tac |
              grep -m 1 -o -x '[[:space:]]*[Bb]ench[ :]\{1,\}[1-9][0-9]\{5,7\}[[:space:]]*' |
              sed 's/[^0-9]//g') || true

            if [ -n "$benchref" ]; then
              break
            fi
          done

          if [ -n "$benchref" ]; then
            echo "benchref=$benchref" >> "$GITHUB_ENV"
            echo "From commit: $hash"
            echo "Reference bench: $benchref"
          else
            echo "No bench found"
          fi

      - name: Verify bench under node
        run: EXE=./DON.js RUN_PREFIX=node ../tests/signature.sh "$benchref"
