name: Check Compilers AVX2

on:
  workflow_call:

jobs:
  CheckCompileAVX2:
    name: ${{ matrix.name }} (AVX2)
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # GCC 10–16 compiler images
          - { name: GCC-10, comp: gcc, cxx: g++, image: "ghcr.io/official-stockfish/compiler-images:gcc-10" }
          - { name: GCC-11, comp: gcc, cxx: g++, image: "ghcr.io/official-stockfish/compiler-images:gcc-11" }
          - { name: GCC-12, comp: gcc, cxx: g++, image: "ghcr.io/official-stockfish/compiler-images:gcc-12" }
          - { name: GCC-13, comp: gcc, cxx: g++, image: "ghcr.io/official-stockfish/compiler-images:gcc-13" }
          - { name: GCC-14, comp: gcc, cxx: g++, image: "ghcr.io/official-stockfish/compiler-images:gcc-14" }
          - { name: GCC-15, comp: gcc, cxx: g++, image: "ghcr.io/official-stockfish/compiler-images:gcc-15" }
          - { name: GCC-16, comp: gcc, cxx: g++, image: "ghcr.io/official-stockfish/compiler-images:gcc-16" }

          # Clang 10 compiler image
          - { name: Clang-10, comp: clang, cxx: clang++, image: "silkeh/clang:10", needs_install: true }

          # Clang 10–17 compiler images
          - { name: Clang-11, comp: clang, cxx: clang++, image: "ghcr.io/official-stockfish/compiler-images:clang-11" }
          - { name: Clang-12, comp: clang, cxx: clang++, image: "ghcr.io/official-stockfish/compiler-images:clang-12" }
          - { name: Clang-13, comp: clang, cxx: clang++, image: "ghcr.io/official-stockfish/compiler-images:clang-13" }
          - { name: Clang-14, comp: clang, cxx: clang++, image: "ghcr.io/official-stockfish/compiler-images:clang-14" }
          - { name: Clang-15, comp: clang, cxx: clang++, image: "ghcr.io/official-stockfish/compiler-images:clang-15" }
          - { name: Clang-16, comp: clang, cxx: clang++, image: "ghcr.io/official-stockfish/compiler-images:clang-16" }
          - { name: Clang-17, comp: clang, cxx: clang++, image: "ghcr.io/official-stockfish/compiler-images:clang-17" }

          # Clang 18–23 compiler images
          - { name: Clang-18, comp: clang, cxx: clang++-18, image: "ghcr.io/official-stockfish/compiler-images:clang-18" }
          - { name: Clang-19, comp: clang, cxx: clang++-19, image: "ghcr.io/official-stockfish/compiler-images:clang-19" }
          - { name: Clang-20, comp: clang, cxx: clang++-20, image: "ghcr.io/official-stockfish/compiler-images:clang-20" }
          - { name: Clang-21, comp: clang, cxx: clang++-21, image: "ghcr.io/official-stockfish/compiler-images:clang-21" }
          - { name: Clang-22, comp: clang, cxx: clang++-22, image: "ghcr.io/official-stockfish/compiler-images:clang-22" }
          - { name: Clang-23, comp: clang, cxx: clang++-23, image: "ghcr.io/official-stockfish/compiler-images:clang-23" }

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install dependencies
        if: ${{ matrix.needs_install }}
        run: |
          apt-get update
          apt-get install -y make git # curl

      - name: Download the network
        working-directory: src
        run: make net

      - name: Build 'AVX2' binary
        working-directory: src
        env:
          EXTRA_CXXFLAGS: "-Werror"
        run: |
          make clean
          make -j build ARCH=x86-64-avx2 COMP="${{ matrix.comp }}" COMPCXX="${{ matrix.cxx }}"

      - name: Smoke test
        working-directory: src
        run: ./DON bench 16 1 6
