name: Upload Binaries

on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  Artifacts:
    name: ${{ matrix.config.name }} ${{ matrix.binary }}
    runs-on: ubuntu-latest
    env:
      SIMPLE_NAME: ${{ matrix.config.simple_name }}
      BINARY: ${{ matrix.binary }}
      EXT: ${{ matrix.config.ext }}
      ARCHIVE_EXT: ${{ matrix.config.archive_ext }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Download artifact from compilation
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ env.SIMPLE_NAME }} ${{ env.BINARY }}
          path: ${{ env.SIMPLE_NAME }} ${{ env.BINARY }}

      - name: Create Package
        run: |
          mkdir DON

      - name: Download wiki
        run: |
          git clone https://github.com/ehsanrashid/DON.wiki.git wiki
          rm -rf wiki/.git
          mv wiki DON/

      - name: Copy files
        run: |
          mv "$SIMPLE_NAME $BINARY" DON-workflow
          cd DON-workflow
          cp -r src ../DON/
          cp -r scripts ../DON/
          cp "DON-$SIMPLE_NAME-$BINARY$EXT" ../DON/
          cp Copying.txt ../DON/
          cp CITATION.cff ../DON/
          cp README.md ../DON/
          cp CONTRIBUTING.md ../DON/

      - name: Make binary executable
        run: chmod +x "./DON/DON-$SIMPLE_NAME-$BINARY$EXT"

      - name: Create tar
        if: startsWith(env.ARCHIVE_EXT, 'tar')
        run: |
          echo "Creating TAR..."
          tar -cavf "DON-$SIMPLE_NAME-$BINARY.$ARCHIVE_EXT" DON

      - name: Create zip
        if: env.ARCHIVE_EXT == 'zip'
        run: |
          echo "Creating ZIP..."
          zip -r "DON-$SIMPLE_NAME-$BINARY.zip" DON

      # Make sure that an old CI run on main doesn't recreate a prerelease
      - name: Check Pullable Commits
        id: check-commits
        run: |
          git fetch origin main
          CHANGES=$(git rev-list HEAD..origin/main --count)
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV

      - name: Get last commit sha
        id: last-commit
        run: echo "COMMIT_SHA=$(git rev-parse HEAD | cut -c 1-8)" >> $GITHUB_ENV

      - name: Get commit date
        id: commit-date
        run: echo "COMMIT_DATE=$(git show -s --date=format:'%Y%m%d' --format=%cd HEAD)" >> $GITHUB_ENV

      - name: Official Release?
        id: official-release
        # Check for "Official release version of DON" in the commit message
        run: |
          if git log -1 --pretty=%B | grep -q "Official release version of DON"; then
            echo "OFFICIAL_RELEASE=true" >> $GITHUB_ENV
          else
            echo "OFFICIAL_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Prerelease
        if: github.ref_name == 'main' && env.CHANGES == '0' && env.OFFICIAL_RELEASE == 'false'
        continue-on-error: true
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          name: DON dev-${{ env.COMMIT_DATE }}-${{ env.COMMIT_SHA }}
          tag_name: DON-dev-${{ env.COMMIT_DATE }}-${{ env.COMMIT_SHA }}
          prerelease: true
          files: DON-${{ env.SIMPLE_NAME }}-${{ env.BINARY }}.${{ env.ARCHIVE_EXT }}
          token: ${{ secrets.token }}

      - name: Release
        if: startsWith(github.ref_name, 'DON_') && github.ref_type == 'tag'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: DON-${{ env.SIMPLE_NAME }}-${{ env.BINARY }}.${{ env.ARCHIVE_EXT }}
          token: ${{ secrets.token }}
